// Still renders of the 3D objects, captured from the real scenes on a GPU:
//   hero E, front pose (the swing-in's first frame) and resting pose, for the desktop and mobile layouts;
//   the three skill objects in their resting pose.
// The page shows these first, and keeps them on devices without GPU acceleration. The script also measures
// where each hero still sits and writes src/styles/stills.css so the stills line up with the live E.
// Needs a real GPU, so run it locally after a build when a 3D object changes: npm run build && npm run stills
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import {chromium} from 'playwright';
import {serveDist} from './serve-dist.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'public', 'media', 'stills');
const CSS = path.join(ROOT, 'src', 'styles', 'stills.css');
const {server, origin} = serveDist();
const angle = {win32: ['--use-angle=d3d11'], darwin: ['--use-angle=metal']}[process.platform] || [];
const browser = await chromium.launch({args: [...angle, '--enable-gpu', '--ignore-gpu-blocklist']});
// Capture only the canvas: no page backgrounds, overlays or stills, and no fade on the canvas itself.
const ISOLATE = 'html,body,.page,.hero,.skill .gl{background:transparent!important}.hero::after,.hero-copy,.hero-foot,.nav,.cursor,.skip,.hero-still{display:none!important}#heroGL{opacity:1!important;transition:none!important}';

async function page(viewport, reduced){
  const p = await browser.newPage({...viewport, reducedMotion: reduced ? 'reduce' : 'no-preference'});
  await p.addInitScript(css => addEventListener('DOMContentLoaded', () => { const s = document.createElement('style'); s.textContent = css; document.head.append(s); }), ISOLATE);
  await p.goto(origin + '/?3d', {waitUntil: 'domcontentloaded'});
  const renderer = await p.evaluate(() => { const g = document.createElement('canvas').getContext('webgl2'); return g && g.getParameter(g.RENDERER); });
  if (!renderer || /swiftshader|llvmpipe|software/i.test(renderer)) throw new Error(`No GPU available (${renderer}); stills must come from a GPU render.`);
  return p;
}

// Trim, save as WebP, and return its placement relative to the hero (in cqh: % of hero height).
async function heroStill(p, name){
  await p.waitForSelector('#heroGL.ready', {timeout: 30000});
  const buf = await p.locator('#heroGL').screenshot({omitBackground: true});
  const {width: W, height: H} = await sharp(buf).metadata();
  const t = await sharp(buf).trim({threshold: 1}).toBuffer({resolveWithObject: true});
  const {width: w, height: h} = t.info, left = -t.info.trimOffsetLeft, top = -t.info.trimOffsetTop;
  await sharp(t.data).webp({quality: 86, alphaQuality: 90}).toFile(path.join(OUT, `${name}.webp`));
  const cq = v => +(v / H * 100).toFixed(2);
  console.log(`${name}.webp ${w}x${h}`);
  return {name, x: cq(left + w / 2 - W / 2), y: cq(top + h / 2 - H / 2), h: cq(h), ratio: `${w}/${h}`};
}

const layouts = {desktop: {viewport: {width: 1440, height: 900}, deviceScaleFactor: 2}, mobile: {viewport: {width: 390, height: 844}, deviceScaleFactor: 3, isMobile: true, hasTouch: true}};
const place = {};
try {
  fs.mkdirSync(OUT, {recursive: true});
  for (const [layout, vp] of Object.entries(layouts)){
    // Front pose: the live E holds its first frame while it crossfades in (hero.js), so capture right away.
    let p = await page(vp, false);
    place[`front-${layout}`] = await heroStill(p, `hero-front-${layout}`);
    await p.close();
    // Resting pose: reduced motion draws the E at rest.
    p = await page(vp, true);
    place[`rest-${layout}`] = await heroStill(p, `hero-rest-${layout}`);
    if (layout === 'desktop') for (const kind of ['bars', 'net', 'stack']){
      const c = p.locator(`[data-scene="${kind}"]`);
      await c.scrollIntoViewIfNeeded(); await p.waitForFunction(k => document.querySelector(`[data-scene="${k}"]`).parentElement.classList.contains('live'), kind);
      await p.waitForTimeout(300);
      await sharp(await c.screenshot({omitBackground: true})).webp({quality: 86, alphaQuality: 90}).toFile(path.join(OUT, `skill-${kind}.webp`));
      console.log(`skill-${kind}.webp`);
    }
    await p.close();
  }
  const rule = (sel, s) => `${sel}{--x:${s.x}cqh;--y:${s.y}cqh;--h:${s.h}cqh;aspect-ratio:${s.ratio};background-image:url(/media/stills/${s.name}.webp)}`;
  fs.writeFileSync(CSS, `/* Generated by scripts/stills.mjs (npm run stills): where each hero still sits, measured from the live render. */
${rule('.hero-still.front', place['front-desktop'])}
${rule('.hero-still.rest', place['rest-desktop'])}
@container (max-width:759px){
  ${rule('.hero-still.front', place['front-mobile'])}
  ${rule('.hero-still.rest', place['rest-mobile'])}
}
`);
  console.log('src/styles/stills.css written');
} finally {
  await browser.close();
  server.close();
}
